package com.blog.entity;
import java.io.Serializable;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * Date: Thu Aug 22 09:39:26 CST 2019.
 *
 * @author (作者名)
 */

public class Comments  implements Serializable {


	private static final long serialVersionUID =  7759552451216043625L;


	/**
	 *  主键
	 */
	private Integer id;

	/**
	 *  文章id
	 */
	private Integer articleRef;

	/**
	 *  评论者id
	 */
	private Integer commentId;

	/**
	 *  父评论者id
	 */
	private Integer parentId;

	/**
	 *  文章作者id
	 */
    
	private Integer authorId;

	/**
	 *  评论时间
	 */
    
	private Date commentTime;

	/**
	 *  评论点赞数
	 */
    
	private Integer commentsLikeCounts;

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getArticleRef() {
		return this.articleRef;
	}

	public void setArticleRef(Integer articleRef) {
		this.articleRef = articleRef;
	}

	public Integer getCommentId() {
		return this.commentId;
	}

	public void setCommentId(Integer commentId) {
		this.commentId = commentId;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public Integer getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(Integer authorId) {
		this.authorId = authorId;
	}

	public Date getCommentTime() {
		return this.commentTime;
	}

	public void setCommentTime(Date commentTime) {
		this.commentTime = commentTime;
	}

	public Integer getCommentsLikeCounts() {
		return this.commentsLikeCounts;
	}

	public void setCommentsLikeCounts(Integer commentsLikeCounts) {
		this.commentsLikeCounts = commentsLikeCounts;
	}

}
