package com.blog.entity;
import java.io.Serializable;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * Date: Thu Aug 22 09:39:26 CST 2019.
 *
 * @author (作者名)
 */

public class LoginLog  implements Serializable {


	private static final long serialVersionUID =  4380911715978781784L;


	/**
	 *    
	 */
     
	private Integer id;

	/**
	 *    
	 */
     
	private Integer userRef;

	/**
	 *    
	 */
     
	private String loginIp;

	/**
	 *    
	 */
     
	private Date loginTime;

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUserRef() {
		return this.userRef;
	}

	public void setUserRef(Integer userRef) {
		this.userRef = userRef;
	}

	public String getLoginIp() {
		return this.loginIp;
	}

	public void setLoginIp(String loginIp) {
		this.loginIp = loginIp;
	}

	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

}
