package com.blog.entity;
import java.io.Serializable;

/**
 * generated by Generate POJOs.groovy 
 * Date: Thu Aug 22 09:39:26 CST 2019.
 *
 * @author (作者名)
 */

public class Resource  implements Serializable {


	private static final long serialVersionUID =  4654959853588410776L;


	/**
	 *   
	 */
    
	private Integer id;

	/**
	 *  资源名称
	 */
    
	private String resourceName;

	/**
	 *  资源对应url
	 */
    
	private String resourceUrl;

	/**
	 *  资源是否可用
	 */
    
	private String isActive;

	/**
	 *  备注
	 */
    
	private String remark;

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getResourceName() {
		return this.resourceName;
	}

	public void setResourceName(String resourceName) {
		this.resourceName = resourceName;
	}

	public String getResourceUrl() {
		return this.resourceUrl;
	}

	public void setResourceUrl(String resourceUrl) {
		this.resourceUrl = resourceUrl;
	}

	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
