package com.blog.entity;
import java.io.Serializable;

/**
 * generated by Generate POJOs.groovy 
 * Date: Thu Aug 22 09:39:26 CST 2019.
 *
 * @author (作者名)
 */

public class RoleUser  implements Serializable {


	private static final long serialVersionUID =  915316878625425539L;


	/**
	 *   
	 */
    
	private Integer id;

	/**
	 *  用户id
	 */
    
	private Integer userRef;

	/**
	 *  角色id
	 */
    
	private Integer roleRef;

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUserRef() {
		return this.userRef;
	}

	public void setUserRef(Integer userRef) {
		this.userRef = userRef;
	}

	public Integer getRoleRef() {
		return this.roleRef;
	}

	public void setRoleRef(Integer roleRef) {
		this.roleRef = roleRef;
	}

}
