package com.blog.entity;
import java.io.Serializable;

/**
 * generated by Generate POJOs.groovy 
 * Date: Thu Aug 22 09:39:26 CST 2019.
 *
 * @author (作者名)
 */

public class RoleResource  implements Serializable {


	private static final long serialVersionUID =  899092368131608924L;


	/**
	 *   
	 */
    
	private Integer id;

	/**
	 *  资源id
	 */
    
	private Integer resourceRef;

	/**
	 *  角色id
	 */
    
	private Integer roleRef;

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getResourceRef() {
		return this.resourceRef;
	}

	public void setResourceRef(Integer resourceRef) {
		this.resourceRef = resourceRef;
	}

	public Integer getRoleRef() {
		return this.roleRef;
	}

	public void setRoleRef(Integer roleRef) {
		this.roleRef = roleRef;
	}

}
