package com.blog.entity;
import java.io.Serializable;

/**
 * generated by Generate POJOs.groovy 
 * Date: Thu Aug 22 09:39:26 CST 2019.
 *
 * @author (作者名)
 */

public class Role  implements Serializable {


	private static final long serialVersionUID =  1733343708354673357L;


	/**
	 *   
	 */
    
	private Integer id;

	/**
	 *  角色id
	 */
    
	private Integer roleRef;

	/**
	 *  角色名称
	 */
    
	private String roleName;

	/**
	 *  角色值
	 */
    
	private String roleValue;

	/**
	 *  角色可访问url
	 */
    
	private String roleUrl;

	/**
	 *  角色是佛否可用
	 */
    
	private String isActive;

	/**
	 *  备注
	 */
    
	private String remark;

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getRoleRef() {
		return this.roleRef;
	}

	public void setRoleRef(Integer roleRef) {
		this.roleRef = roleRef;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getRoleValue() {
		return this.roleValue;
	}

	public void setRoleValue(String roleValue) {
		this.roleValue = roleValue;
	}

	public String getRoleUrl() {
		return this.roleUrl;
	}

	public void setRoleUrl(String roleUrl) {
		this.roleUrl = roleUrl;
	}

	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
