package com.blog.entity;
import java.io.Serializable;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * Date: Thu Aug 22 09:39:26 CST 2019.
 *
 * @author (作者名)
 */

public class Upvote  implements Serializable {


	private static final long serialVersionUID =  9212406856535703608L;


	/**
	 *  主键
	 */
    
	private Integer id;

	/**
	 *  用户id
	 */
    
	private Integer userRef;

	/**
	 *  文章id
	 */
    
	private Integer articleId;

	/**
	 *  喜欢
	 */
    
	private String isLike;

	/**
	 *  不喜欢
	 */
    
	private String dislike;

	/**
	 *  点赞时间
	 */
    
	private Date upvoteTime;

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUserRef() {
		return this.userRef;
	}

	public void setUserRef(Integer userRef) {
		this.userRef = userRef;
	}

	public Integer getArticleId() {
		return this.articleId;
	}

	public void setArticleId(Integer articleId) {
		this.articleId = articleId;
	}

	public String getIsLike() {
		return this.isLike;
	}

	public void setIsLike(String isLike) {
		this.isLike = isLike;
	}

	public String getDislike() {
		return this.dislike;
	}

	public void setDislike(String dislike) {
		this.dislike = dislike;
	}

	public Date getUpvoteTime() {
		return this.upvoteTime;
	}

	public void setUpvoteTime(Date upvoteTime) {
		this.upvoteTime = upvoteTime;
	}

}
