package com.blog.entity;
import java.io.Serializable;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * Date: Thu Aug 22 09:39:26 CST 2019.
 *
 * @author (作者名)
 */

public class UserArticle  implements Serializable {


	private static final long serialVersionUID =  4940142988632922556L;


	/**
	 *  null
	 */
   null
	private Integer id;

	/**
	 *  用户id
	 */
   null
	private Integer userRef;

	/**
	 *  标题
	 */
   null
	private String title;

	/**
	 *  分类
	 */
   null
	private String class;

	/**
	 *  内容
	 */
   null
	private String content;

	/**
	 *  是否私有
	 */
   null
	private String isPrivate;

	/**
	 *  上传时间
	 */
   null
	private Date uploadTime;

	/**
	 *  用户头像
	 */
   null
	private String userHeadPhoto;

	/**
	 *  用户昵称
	 */
   null
	private String userNick;

	/**
	 *  点赞数
	 */
   null
	private Integer likeCounts;

	/**
	 *  不喜欢数
	 */
   null
	private Integer dislikeCounts;

	/**
	 *  评论数
	 */
   null
	private Integer commentsCounts;

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUserRef() {
		return this.userRef;
	}

	public void setUserRef(Integer userRef) {
		this.userRef = userRef;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getClass() {
		return this.class;
	}

	public void setClass(String class) {
		this.class = class;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getIsPrivate() {
		return this.isPrivate;
	}

	public void setIsPrivate(String isPrivate) {
		this.isPrivate = isPrivate;
	}

	public Date getUploadTime() {
		return this.uploadTime;
	}

	public void setUploadTime(Date uploadTime) {
		this.uploadTime = uploadTime;
	}

	public String getUserHeadPhoto() {
		return this.userHeadPhoto;
	}

	public void setUserHeadPhoto(String userHeadPhoto) {
		this.userHeadPhoto = userHeadPhoto;
	}

	public String getUserNick() {
		return this.userNick;
	}

	public void setUserNick(String userNick) {
		this.userNick = userNick;
	}

	public Integer getLikeCounts() {
		return this.likeCounts;
	}

	public void setLikeCounts(Integer likeCounts) {
		this.likeCounts = likeCounts;
	}

	public Integer getDislikeCounts() {
		return this.dislikeCounts;
	}

	public void setDislikeCounts(Integer dislikeCounts) {
		this.dislikeCounts = dislikeCounts;
	}

	public Integer getCommentsCounts() {
		return this.commentsCounts;
	}

	public void setCommentsCounts(Integer commentsCounts) {
		this.commentsCounts = commentsCounts;
	}

}
