package com.blog.entity;
import java.io.Serializable;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * Date: Thu Aug 22 09:39:26 CST 2019.
 *
 * @author (作者名)
 */

public class UserInfo  implements Serializable {


	private static final long serialVersionUID =  6847014399521833942L;


	/**
	 *   
	 */
    
	private Integer id;

	/**
	 *  用户id
	 */
    
	private Integer userRef;

	/**
	 *  用户昵称
	 */
    
	private String userName;

	/**
	 *  性别
	 */
    
	private String sex;

	/**
	 *  用户生日
	 */
    
	private Date birthday;

	/**
	 *  用户爱好
	 */
    
	private String hobby;

	/**
	 *  用户地址
	 */
    
	private String address;

	/**
	 *   
	 */
    
	private String provice;

	/**
	 *   
	 */
    
	private String city;

	/**
	 *   
	 */
    
	private String district;

	/**
	 *   
	 */
    
	private String street;

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUserRef() {
		return this.userRef;
	}

	public void setUserRef(Integer userRef) {
		this.userRef = userRef;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getHobby() {
		return this.hobby;
	}

	public void setHobby(String hobby) {
		this.hobby = hobby;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getProvice() {
		return this.provice;
	}

	public void setProvice(String provice) {
		this.provice = provice;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

}
