package com.blog.entity;
import java.io.Serializable;

/**
 * generated by Generate POJOs.groovy 
 * Date: Thu Aug 22 09:39:26 CST 2019.
 *
 * @author (作者名)
 */

public class User  implements Serializable {


	private static final long serialVersionUID =  2283156625285497717L;


	/**
	 *   
	 */
    
	private Integer id;

	/**
	 *  邮箱
	 */
    
	private String email;

	/**
	 *  密码
	 */
    
	private String password;

	/**
	 *  电话
	 */
    
	private String phone;

	/**
	 *  昵称
	 */
    
	private String nickName;

	/**
	 *  用户状态
	 */
    
	private String state;

	/**
	 *  用户头像
	 */
    
	private String imgUrl;

	/**
	 *  是否可用
	 */
    
	private String isEnable;

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getImgUrl() {
		return this.imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	public String getIsEnable() {
		return this.isEnable;
	}

	public void setIsEnable(String isEnable) {
		this.isEnable = isEnable;
	}

}
